services:
    _defaults:
        autowire: true
        autoconfigure: true

    Codyas\Toolbox\Controller\CrudController:
        tags: ['controller.service_arguments']

    Codyas\Toolbox\Twig\CodyasExtension:
        arguments:
            $bundleConfig: '%codyas_toolbox_config%'
